name: Continuous Integration

on: [push]

jobs:
  ci_test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: |
          npm install
      - name: npm test
        run: |
          npm test